version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "5050:80"
    depends_on:
      - postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_app
    restart: always
    environment:
      APP_PORT: "8080"
      DB_DRIVER: "postgres"
      DB_USER: "admin"
      DB_PASSWORD: "123456"
      DB_NAME: "payment_db"
      DB_HOST: "postgres"
      DB_PORT: "5432"
      DB_SSL_MODE: "disable"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - postgres
    command: air

volumes:
  postgres_data:
